[package]
name = "exo-class-file"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3"
exo-parser = { path = "./exo-parser" }
fnv = "1.0"