[workspace]
members = [
    "exo-class-file",
    "exo-class-file/exo-parser",
    "exo-jvm",
    "exo-jvm/src/nugc/nugc-derive",
    "java-compiler",
    "java-compiler/java-compiler-derive",
    "exo-java-bin"
]