[package]
name = "exo-class-file-fuzz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
afl = "*"
exo-class-file = { path = "../exo-class-file" }